# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563215999b40556e7b6927e557aaf39cc7eabcc8234467b8dc0c2caa1fd32bb08554ac38eb38fdc16f0e2c3ee88d04c00b43398f8dfb9a212c88a9c730c74442

test:
  secret_key_base: da7a8da395ecb71efbe40dee7b73c6610e2a4dc183b2b3c0ac5ae6c10275dace20e7d02929cca280d5a974d5b1af2547d7283da447239e4bf7623879832bb29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
